### ISSUE TITLE
Support for Dynamic Skin Replacement in Spine Using Additional Atlas Regions

### ISSUE THREAD

**Issue by johanzhu** [galacean/engine-spine#110]
## 背景
Spine 是天然支持换肤的，但是只能够基于原始导出的图集来进行换肤，比如：

![image](https://github.com/user-attachments/assets/b6100675-5af5-4ef9-830c-796b69925698)

这是官方混搭示例的图集，无论是混搭部件，亦或者是整体的皮肤替换都是基于导出的这一张图集进行操作的。

然而，当皮肤数量过多时，仅靠导出的原始图集是不够的，还需要通过动态加载额外的图集来进行部件的替换，也就是“动态换肤”。

## 调研
需要动态换肤的场景有两种：动态整体换肤，动态局部换肤。这两种情况的实现方案也有不同。

### 动态整体换肤
spine forum 相关的帖子如下：

[多个 spine 共享同一个动作](https://zh.esotericsoftware.com/forum/d/15368-%E5%A4%9A%E4%B8%AAspine%E5%85%B1%E4%BA%AB%E4%B8%80%E5%A5%97%E9%AA%A8%E9%AA%BC%E5%8A%A8%E4%BD%9C/5)

[拥有很多很多图片的 spine 角色](https://zh.esotericsoftware.com/forum/d/24356-spine-character-with-many-many-images/2)

[运行时替换 atlas](https://zh.esotericsoftware.com/forum/d/18098-runtime-change-spineatlasasset/2)

对于动态整体换肤，产生这个问题的根因是动画的皮肤数量过多，仅使用静态导出的图集，内存是不够的。所以需要动态加载新的图集以实现换肤的需求。

spine运行时架构：https://zh.esotericsoftware.com/spine-runtime-architecture

#### 调研与方案
根据调研，实现动态整体换肤的方案无非下面几个方案：

1. 替换整个 spine 动画素材 ：[https://zh.esotericsoftware.com/forum/d/17537-how-to-to-change-to-another-skeletondataasset-in-game/6](https://zh.esotericsoftware.com/forum/d/17537-how-to-to-change-to-another-skeletondataasset-in-game/6)
2. 仅替换 atlas ：[https://zh.esotericsoftware.com/forum/d/18098-runtime-change-spineatlasasset](https://zh.esotericsoftware.com/forum/d/18098-runtime-change-spineatlasasset)
3. 仅替换贴图

下面是每种方案的调研与结论：

方案1: 已支持。

方案2:待实现。

调研：
unity:
unity 提供了一个 createRuntimeInstance 方法来创建一个 SkeletonDataAsset 对象，接收 skeleton 文件和 atlas 图集文件，创建新的SkeletonDataAsset：
https://github.com/EsotericSoftware/spine-runtimes/blob/4.2/spine-unity/Assets/Spine/Runtime/spine-unity/Asset%20Types/SkeletonDataAsset.cs
https://github.com/EsotericSoftware/spine-runtimes/blob/4.2/spine-unity/Assets/Spine/Runtime/spine-unity/Components/SkeletonRenderer.cs#L455

![image](https://github.com/user-attachments/assets/0f0ebeee-b185-47ac-9707-1e448ad66d4d)

优势：提供了方法在运行时创建并替换 spine 动画资产，灵活性强。
劣势：但是，运行时创建资产时，需要手动指定 skeleton 和 atlas 的关联关系。

ue：
ue 没有对外提供更新的方法，但是引擎内部有对应的实现，当 atlas 和 skeleton 两个数据发生改变时，会重新调用 GetSkeletonData 来加载并重新创建 Skeleton 和 AnimationState 对象，这和 unity 的操作是一样的。只不过 unity 会在 initialize 方法中执行加载和创建的逻辑
![image](https://github.com/user-attachments/assets/92db48a5-30fa-4f82-a3c2-1edc384b793c)

劣势：ue 替换素材的方法没有对外暴露，无法运行时手动创建 spine 动画资产。

godot：
gotot 提供了一个 set_skeleton_data_res 方法用于设置 spine 资产。当资产修改后，会在内部调用一个更新方法，重新执行加载逻辑：
![image](https://github.com/user-attachments/assets/8582f071-b5d0-4726-838a-393af04e2a87)

劣势：Godot 替换素材的 skeleton文件与atlas文件的关联关系无法修改，重新设置资产只能设置加载完毕的  skeleton_data_res 对象，灵活性没有 unity 高。

pixi
pixi 动态替换 atlas，需要重新加载骨架和图集素材，调用 from 方法重新创建新的 spine 动画对象。
![image](https://github.com/user-attachments/assets/4b19809e-2925-40b2-9d56-ad6534f848a2)

劣势：pixi 中，skeleton 和 atlas 的关联关系，只能手动建立。由于缺乏编辑器上传流程，假设文件不对应，会导致无法渲染或者渲染出错。

cocos
cocos 替换 atlas 的方式和 unity 类似，也需要重新创建新的 skelentonData 素材：
![image](https://github.com/user-attachments/assets/75e4df9c-929c-497a-af19-a782a77314c9)

优势：灵活性强，能够运行时修改 spine 动画资产，还可以自定义 atlas 关联的图片素材的路径。
劣势：不同资产的关联关系需要手动建立。假设文件不对应，会导致无法渲染或者渲染出错。

laya
laya 没有提供替换 atlas 的方式，只能加载新的 spine 动画素材:
![image](https://github.com/user-attachments/assets/a9596f54-a466-4bc2-94f0-7bebc19c125c)

劣势：与 godot 类似，无法修改 skeleton 和 atlas 文件的关联关系。

结论：
综合调研，最好的方案需要支持以下功能：
1. 提供在运行时创建运行时使用的资产的能力
2. 能够加载已经建立了关联关系的资产
3. 提供能力手动建立资产间的关联关系（skeletonData -> skeleton + textureAtlas ）(textureAtlas -> atlas + texture)

具体方案：
1和2目前已经支持：
Galacean 的编辑器资产和运行时使用的资产是通过 Loader 来完成转化的。目前skeletonDataAsset，spineAtlasAsset都有对应的 Loader。即已经存在方法在运行时创建运行时使用的资产了。（ 这种情况下，素材的关联关系已经在上传素材时就确定好了）
这几种资产的运行时资产如下：
skeletonDataAsset 的运行时资产是SkeletonDataResource
spineAtlasAsset 的运行时资产是TextureAtlas
texture的运行时资产是 Texture2D

3.提供新的创建运行时使用的资产的方法，并且支持手动建立资产关联关系。
- 在 LoaderUtils 中增加一个 createSpineResource 方法，用于创建 SpineResource 对象。参数是 skeleton 的数据以及 TextureAtlas对象。

createSpineResource(engine: Engine, skeletonRawData: string | ArrayBuffer, textureAtlas: TextureAtlas, name?: string): SpineResource {} 

- 在 LoaderUtils 中增加一个 createTextureAtlas 方法，用于创建 TextureAtlas 对象。参数是 atlas 的文本和 texture 的地址。

createTextureAtlas(atlasText: string, textures: Texture2D[]): TextureAtlas {}

方案3:
支持，但不合适。
需要视觉保证贴图的布局和之前保持不变，对于视觉来说实现起来不太现实，对于换肤来说也不够灵活。不是合适的方式。
但是通过 getMaterial 替换贴图也能够实现。

### 动态局部换肤
[Spine 4.0 实现不同图集下的局部换装](https://zh.esotericsoftware.com/forum/d/17604-spine-40-%E5%AE%9E%E7%8E%B0%E4%B8%8D%E5%90%8C%E5%9B%BE%E9%9B%86%E4%B8%8B%E7%9A%84%E5%B1%80%E9%83%A8%E6%8D%A2%E8%A3%85)

[能否有模块化的资产？](https://zh.esotericsoftware.com/forum/d/15205-can-there-be-quotmodular-assetsquot/3)

[请问例子AtlasRegionAttacher的Spine源文件在哪里下载](https://zh.esotericsoftware.com/forum/d/18385-%E8%AF%B7%E9%97%AE%E4%BE%8B%E5%AD%90atlasregionattacher%E7%9A%84spine%E6%BA%90%E6%96%87%E4%BB%B6%E5%9C%A8%E5%93%AA%E9%87%8C%E4%B8%8B%E8%BD%BD)

动态局部换装，也就是给当前的 spine 动画分配来自于另一个图集中的附件。
这里先图解一下“给当前的 spine 动画分配来自于另一个图集中的附件”这句话的含义：
![image](https://github.com/user-attachments/assets/c418ec4b-3d33-423b-8087-474a2e36bc64)

见上图，一个 spine 动画对应一个 atlas，一个 atlas 对应一个或多个 atlas page。一个 page 内有多个 region。 region 所存储的 texture 和 page 是对应的。
page 不可能无限增多，所以此时就需要动态加载额外的 atlas 来加载皮肤部件了。
替换的方案就是使用新的贴图的附件，来替换原有的附件。以下则是 Unity 和 pixi 的实现具体方案。

#### 调研
使用额外的贴图创建附件并替换原有附件，这样的操作只有 Unity 和 Pixi 有对应的实现：

+ unity

unity 的 AtlasRegionAttacher.cs 的实现：

附件克隆插件：

[https://github.com/EsotericSoftware/spine-runtimes/blob/4.2/spine-unity/Assets/Spine/Runtime/spine-unity/Utility/AttachmentCloneExtensions.cs](https://github.com/EsotericSoftware/spine-runtimes/blob/4.2/spine-unity/Assets/Spine/Runtime/spine-unity/Utility/AttachmentCloneExtensions.cs)

附件区域插件：

[https://github.com/EsotericSoftware/spine-runtimes/blob/4.2/spine-unity/Assets/Spine/Runtime/spine-unity/Utility/AttachmentRegionExtensions.cs](https://github.com/EsotericSoftware/spine-runtimes/blob/4.2/spine-unity/Assets/Spine/Runtime/spine-unity/Utility/AttachmentRegionExtensions.cs)

unity 提供了两个方法基于 atlas 来创建新的附件。

如果原本的插槽存在附件，可以通过重新设置 region，来实现贴图的替换。

如果原本的插槽存在不存在附件，则需要新创建一个 RegionAttachment。

创建好新的附件后，通过 API 替换原有附件即可实现局部换肤。

优势：能够基于 spine core 本身的 API 就实现局部的动态换肤。不但可以基于 spine 图集创建新的附件，还可以使用 Unity 的Sprite 来创建新的附件，灵活性非常强。

+ pixi-spine

pixi 的实现：

[https://github.com/pixijs/spine/blob/master/packages/base/src/SpineBase.ts#L647](https://github.com/pixijs/spine/blob/master/packages/base/src/SpineBase.ts#L647)

pixi 的实现原理和 unity 类似，但是 pixi 无需设置附件的 region。

因为 pixi 在渲染时，直接把新的 region 存储到当前渲染的 Display 对象上了，需要替换 texture 时，直接拿存的 region 里的 texture 即可。

当需要 hack texture 时，直接 new 新的 TextureRegion 对象并重新存储至 Display 对象，然后设置 texture 即可。

![image](https://github.com/user-attachments/assets/d18a7d70-6ca1-4f09-b41b-b656a04e9de7)

优势：
可以摆脱 spine 图集，精灵这些限制，直接替换区域的贴图。

劣势：
pixi 的实现和 pixi runtime 的绑定比较死，依赖其 sprite 以及 mesh 对象。而 unity 的实现还是基于 spine-core 进行的修改。

#### 方案

结合的调研，基于 Spine 的图集来实现局部换肤实现的成本低，而且可以使用 Spine 编辑器来打包图集，设计师可以在 Spine 中把需要换肤的部件打包成一个个单独的图集，比如：武器图集，衣服图集，头发图集。然后在脚本中，基于图集区域创建的新的附件替换。
这种方案的缺点是，当局部换肤时，需要加载整个附件图集，不过也可以根据合理的拆分，来最小化加载所需的图集资源。

而另一种方案，使用 Sprite 创建附件的方式，每替换一个附件，都要生成一个新的 material，内存中会存在很多的 Texture。所以需要通过 repack 来降低内存。
repack 实现的成本就比较高了，如何在运行时打包需要考虑很多细节。Unity 通过插件的方式，额外写了一套打包逻辑，在运行时打包一个新的运行时图集（其实是一个 Texture2D）。
实现这种方案需要考虑引擎本身的图集打包逻辑与 spine 的结合，成本较高。

综上考虑，目前优先实现第一种方案，封装两个 util 方法来基于 AtlasRegion 创建新的附件，一个是基于已有的附件克隆，一个是直接创建一个全新的区域附件：

```typescript

cloneAttachmentWithAtlasRegion(
  attachment: Attachment,
  region: TextureAtlasRegion,
  scale?: number,
)

```

```typescript
atlasRegionToAttachment(
  region: TextureAtlasRegion,
  attachmentName: string,
  scale?: number,
  rotation?: number,
)
```

创建出附件后，直接替换原有的 attachment 即可。

```typescript
const slot = skeleton.findSlot(slotName); // 找到要替换附件的插槽
const originAttachment = slot.attachment; // 获取原本插槽里的附件
const atlasRegion = atlas.FindRegion(regionName); // 找到atlas用于替换的区域

// 基于region，创建或者克隆一个新的附件
const newAttachment = cloneAttachmentWithAtlasRegion(originAttachment, atlasRegion);
// 或者 const newAttachment = atlasRegionToAttachment(atlasRegion, 'attachmentName');

// 替换附件
slot.attachment = newAttachment;
```

更新附件的方式也与官方推荐的方法一致：

[https://zh.esotericsoftware.com/spine-runtime-skeletons#%E6%9B%B4%E6%8D%A2%E9%99%84%E4%BB%B6](https://zh.esotericsoftware.com/spine-runtime-skeletons#%E6%9B%B4%E6%8D%A2%E9%99%84%E4%BB%B6)

获取 atlasRegion 的方法也很简单，基于新的上传流程（[https://github.com/galacean/editor/pull/2895](https://github.com/galacean/editor/pull/2895)），能够单独上传 atlas 文件了。

```typescript
const textureAtlas = await engine.resourceManager.load(
  {
    url: 'http://spine-boy.atlas',
    type: 'spineAtlas',
  },
);
```

**Comment by singlecoder** [comment]
附加 SpineAtlas 贴图这几个的关系可以补充一个图示

**Comment by johanzhu** [comment]
> 附加 SpineAtlas 贴图这几个的关系可以补充一个图示

👌 这里确实没有讲解清楚，我把spine的这几个类的关系用图画一下
